# See https://github.com/actions/labeler

example:
- examples/**/*

'🚨 action':
- .github/workflows/**

docs:
- docs/**

test:
- packages/**/*.test.js

i18n:
- any:
  - 'docs/src/pages/*/**'
  - '!docs/src/pages/core-concepts/**'
  - '!docs/src/pages/guides/**'
  - '!docs/src/pages/migration/**'
  - '!docs/src/pages/reference/**'

core:
- packages/astro/**

create-astro:
- packages/create-astro/**

markdown:
- packages/markdown/**

renderer:
- packages/renderers/**

framework-lit:
- packages/renderers/renderer-lit/**

framework-preact:
- packages/renderers/renderer-preact/**

framework-react:
- packages/renderers/renderer-react/**

framework-solid:
- packages/renderers/renderer-solid/**

framework-svelte:
- packages/renderers/renderer-svelte/**

framework-vue:
- packages/renderers/renderer-vue/**
