name: Changelog

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines
        env:
          CI: true

      - name: Create release PR
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
